package org.insightcentre.converter.impl.protegen.methylation.impl.impl;


import java.util.Collection;

import org.insightcentre.converter.impl.protegen.methylation.impl.Gene_Name;
import org.insightcentre.converter.impl.protegen.methylation.impl.Vocabulary;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultGene_Name <br>
 * @version generated on Sat Oct 31 12:49:53 GMT 2015 by pc
 */
public class DefaultGene_Name extends WrappedIndividualImpl implements Gene_Name {

    public DefaultGene_Name(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#GeneNameLiteral
     */
     
    public Collection<? extends Object> getGeneNameLiteral() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GENENAMELITERAL, Object.class);
    }

    public boolean hasGeneNameLiteral() {
		return !getGeneNameLiteral().isEmpty();
    }

    public void addGeneNameLiteral(Object newGeneNameLiteral) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GENENAMELITERAL, newGeneNameLiteral);
    }

    public void removeGeneNameLiteral(Object oldGeneNameLiteral) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GENENAMELITERAL, oldGeneNameLiteral);
    }


}
