package org.insightcentre.converter.impl.protegen.methylation.impl.impl;


import java.util.Collection;

import org.insightcentre.converter.impl.protegen.methylation.impl.Chromosome;
import org.insightcentre.converter.impl.protegen.methylation.impl.Gene_Name;
import org.insightcentre.converter.impl.protegen.methylation.impl.Methylation;
import org.insightcentre.converter.impl.protegen.methylation.impl.Vocabulary;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMethylation <br>
 * @version generated on Sat Oct 31 12:49:53 GMT 2015 by pc
 */
public class DefaultMethylation extends WrappedIndividualImpl implements Methylation {

    public DefaultMethylation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://cosmic.sels.insight.org/schema/Methylation#Chromosome
     */
     
    public Collection<? extends Chromosome> getChromosome() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CHROMOSOME,
                                               DefaultChromosome.class);
    }

    public boolean hasChromosome() {
	   return !getChromosome().isEmpty();
    }

    public void addChromosome(Chromosome newChromosome) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CHROMOSOME,
                                       newChromosome);
    }

    public void removeChromosome(Chromosome oldChromosome) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CHROMOSOME,
                                          oldChromosome);
    }


    /* ***************************************************
     * Object Property http://cosmic.sels.insight.org/schema/Methylation#Gene_Name
     */
     
    public Collection<? extends Gene_Name> getGene_Name() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_GENE_NAME,
                                               DefaultGene_Name.class);
    }

    public boolean hasGene_Name() {
	   return !getGene_Name().isEmpty();
    }

    public void addGene_Name(Gene_Name newGene_Name) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_GENE_NAME,
                                       newGene_Name);
    }

    public void removeGene_Name(Gene_Name oldGene_Name) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_GENE_NAME,
                                          oldGene_Name);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Fragment_Id
     */
     
    public Collection<? extends Object> getFragment_Id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FRAGMENT_ID, Object.class);
    }

    public boolean hasFragment_Id() {
		return !getFragment_Id().isEmpty();
    }

    public void addFragment_Id(Object newFragment_Id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FRAGMENT_ID, newFragment_Id);
    }

    public void removeFragment_Id(Object oldFragment_Id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FRAGMENT_ID, oldFragment_Id);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Histology_Subtype_1
     */
     
    public Collection<? extends Object> getHistology_Subtype_1() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HISTOLOGY_SUBTYPE_1, Object.class);
    }

    public boolean hasHistology_Subtype_1() {
		return !getHistology_Subtype_1().isEmpty();
    }

    public void addHistology_Subtype_1(Object newHistology_Subtype_1) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HISTOLOGY_SUBTYPE_1, newHistology_Subtype_1);
    }

    public void removeHistology_Subtype_1(Object oldHistology_Subtype_1) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HISTOLOGY_SUBTYPE_1, oldHistology_Subtype_1);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Histology_Subtype_3
     */
     
    public Collection<? extends Object> getHistology_Subtype_3() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HISTOLOGY_SUBTYPE_3, Object.class);
    }

    public boolean hasHistology_Subtype_3() {
		return !getHistology_Subtype_3().isEmpty();
    }

    public void addHistology_Subtype_3(Object newHistology_Subtype_3) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HISTOLOGY_SUBTYPE_3, newHistology_Subtype_3);
    }

    public void removeHistology_Subtype_3(Object oldHistology_Subtype_3) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HISTOLOGY_SUBTYPE_3, oldHistology_Subtype_3);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Id_Study
     */
     
    public Collection<? extends Object> getId_Study() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID_STUDY, Object.class);
    }

    public boolean hasId_Study() {
		return !getId_Study().isEmpty();
    }

    public void addId_Study(Object newId_Study) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID_STUDY, newId_Study);
    }

    public void removeId_Study(Object oldId_Study) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID_STUDY, oldId_Study);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Position
     */
     
    public Collection<? extends Object> getPosition() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POSITION, Object.class);
    }

    public boolean hasPosition() {
		return !getPosition().isEmpty();
    }

    public void addPosition(Object newPosition) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POSITION, newPosition);
    }

    public void removePosition(Object oldPosition) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POSITION, oldPosition);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Primary_Histology
     */
     
    public Collection<? extends Object> getPrimary_Histology() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PRIMARY_HISTOLOGY, Object.class);
    }

    public boolean hasPrimary_Histology() {
		return !getPrimary_Histology().isEmpty();
    }

    public void addPrimary_Histology(Object newPrimary_Histology) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PRIMARY_HISTOLOGY, newPrimary_Histology);
    }

    public void removePrimary_Histology(Object oldPrimary_Histology) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PRIMARY_HISTOLOGY, oldPrimary_Histology);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Site_Subtype_1
     */
     
    public Collection<? extends Object> getSite_Subtype_1() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SITE_SUBTYPE_1, Object.class);
    }

    public boolean hasSite_Subtype_1() {
		return !getSite_Subtype_1().isEmpty();
    }

    public void addSite_Subtype_1(Object newSite_Subtype_1) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SITE_SUBTYPE_1, newSite_Subtype_1);
    }

    public void removeSite_Subtype_1(Object oldSite_Subtype_1) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SITE_SUBTYPE_1, oldSite_Subtype_1);
    }


    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/Methylation#Site_Subtype_3
     */
     
    public Collection<? extends Object> getSite_Subtype_3() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SITE_SUBTYPE_3, Object.class);
    }

    public boolean hasSite_Subtype_3() {
		return !getSite_Subtype_3().isEmpty();
    }

    public void addSite_Subtype_3(Object newSite_Subtype_3) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SITE_SUBTYPE_3, newSite_Subtype_3);
    }

    public void removeSite_Subtype_3(Object oldSite_Subtype_3) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SITE_SUBTYPE_3, oldSite_Subtype_3);
    }


}
