package org.insightcentre.converter.impl.protegen.completefusionexport.impl;


import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Complete_Fusion_Export <br>
 * @version generated on Fri Nov 06 12:26:57 GMT 2015 by pc
 */

public interface Complete_Fusion_Export extends WrappedIndividual {

    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Id
     */
     
    /**
     * Gets all property values for the Fusion_Id property.<p>
     * 
     * @returns a collection of values for the Fusion_Id property.
     */
    Collection<? extends Fusion_Id> getFusion_Id();

    /**
     * Checks if the class has a Fusion_Id property value.<p>
     * 
     * @return true if there is a Fusion_Id property value.
     */
    boolean hasFusion_Id();

    /**
     * Adds a Fusion_Id property value.<p>
     * 
     * @param newFusion_Id the Fusion_Id property value to be added
     */
    void addFusion_Id(Fusion_Id newFusion_Id);

    /**
     * Removes a Fusion_Id property value.<p>
     * 
     * @param oldFusion_Id the Fusion_Id property value to be removed.
     */
    void removeFusion_Id(Fusion_Id oldFusion_Id);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Type
     */
     
    /**
     * Gets all property values for the Fusion_Type property.<p>
     * 
     * @returns a collection of values for the Fusion_Type property.
     */
    Collection<? extends Object> getFusion_Type();

    /**
     * Checks if the class has a Fusion_Type property value.<p>
     * 
     * @return true if there is a Fusion_Type property value.
     */
    boolean hasFusion_Type();

    /**
     * Adds a Fusion_Type property value.<p>
     * 
     * @param newFusion_Type the Fusion_Type property value to be added
     */
    void addFusion_Type(Object newFusion_Type);

    /**
     * Removes a Fusion_Type property value.<p>
     * 
     * @param oldFusion_Type the Fusion_Type property value to be removed.
     */
    void removeFusion_Type(Object oldFusion_Type);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Histology_Subtype_1
     */
     
    /**
     * Gets all property values for the Histology_Subtype_1 property.<p>
     * 
     * @returns a collection of values for the Histology_Subtype_1 property.
     */
    Collection<? extends Object> getHistology_Subtype_1();

    /**
     * Checks if the class has a Histology_Subtype_1 property value.<p>
     * 
     * @return true if there is a Histology_Subtype_1 property value.
     */
    boolean hasHistology_Subtype_1();

    /**
     * Adds a Histology_Subtype_1 property value.<p>
     * 
     * @param newHistology_Subtype_1 the Histology_Subtype_1 property value to be added
     */
    void addHistology_Subtype_1(Object newHistology_Subtype_1);

    /**
     * Removes a Histology_Subtype_1 property value.<p>
     * 
     * @param oldHistology_Subtype_1 the Histology_Subtype_1 property value to be removed.
     */
    void removeHistology_Subtype_1(Object oldHistology_Subtype_1);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Histology_Subtype_3
     */
     
    /**
     * Gets all property values for the Histology_Subtype_3 property.<p>
     * 
     * @returns a collection of values for the Histology_Subtype_3 property.
     */
    Collection<? extends Object> getHistology_Subtype_3();

    /**
     * Checks if the class has a Histology_Subtype_3 property value.<p>
     * 
     * @return true if there is a Histology_Subtype_3 property value.
     */
    boolean hasHistology_Subtype_3();

    /**
     * Adds a Histology_Subtype_3 property value.<p>
     * 
     * @param newHistology_Subtype_3 the Histology_Subtype_3 property value to be added
     */
    void addHistology_Subtype_3(Object newHistology_Subtype_3);

    /**
     * Removes a Histology_Subtype_3 property value.<p>
     * 
     * @param oldHistology_Subtype_3 the Histology_Subtype_3 property value to be removed.
     */
    void removeHistology_Subtype_3(Object oldHistology_Subtype_3);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Primary_Site
     */
     
    /**
     * Gets all property values for the Primary_Site property.<p>
     * 
     * @returns a collection of values for the Primary_Site property.
     */
    Collection<? extends Object> getPrimary_Site();

    /**
     * Checks if the class has a Primary_Site property value.<p>
     * 
     * @return true if there is a Primary_Site property value.
     */
    boolean hasPrimary_Site();

    /**
     * Adds a Primary_Site property value.<p>
     * 
     * @param newPrimary_Site the Primary_Site property value to be added
     */
    void addPrimary_Site(Object newPrimary_Site);

    /**
     * Removes a Primary_Site property value.<p>
     * 
     * @param oldPrimary_Site the Primary_Site property value to be removed.
     */
    void removePrimary_Site(Object oldPrimary_Site);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Pubmed_PMID
     */
     
    /**
     * Gets all property values for the Pubmed_PMID property.<p>
     * 
     * @returns a collection of values for the Pubmed_PMID property.
     */
    Collection<? extends Object> getPubmed_PMID();

    /**
     * Checks if the class has a Pubmed_PMID property value.<p>
     * 
     * @return true if there is a Pubmed_PMID property value.
     */
    boolean hasPubmed_PMID();

    /**
     * Adds a Pubmed_PMID property value.<p>
     * 
     * @param newPubmed_PMID the Pubmed_PMID property value to be added
     */
    void addPubmed_PMID(Object newPubmed_PMID);

    /**
     * Removes a Pubmed_PMID property value.<p>
     * 
     * @param oldPubmed_PMID the Pubmed_PMID property value to be removed.
     */
    void removePubmed_PMID(Object oldPubmed_PMID);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Site_Subtype_1
     */
     
    /**
     * Gets all property values for the Site_Subtype_1 property.<p>
     * 
     * @returns a collection of values for the Site_Subtype_1 property.
     */
    Collection<? extends Object> getSite_Subtype_1();

    /**
     * Checks if the class has a Site_Subtype_1 property value.<p>
     * 
     * @return true if there is a Site_Subtype_1 property value.
     */
    boolean hasSite_Subtype_1();

    /**
     * Adds a Site_Subtype_1 property value.<p>
     * 
     * @param newSite_Subtype_1 the Site_Subtype_1 property value to be added
     */
    void addSite_Subtype_1(Object newSite_Subtype_1);

    /**
     * Removes a Site_Subtype_1 property value.<p>
     * 
     * @param oldSite_Subtype_1 the Site_Subtype_1 property value to be removed.
     */
    void removeSite_Subtype_1(Object oldSite_Subtype_1);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Site_Subtype_3
     */
     
    /**
     * Gets all property values for the Site_Subtype_3 property.<p>
     * 
     * @returns a collection of values for the Site_Subtype_3 property.
     */
    Collection<? extends Object> getSite_Subtype_3();

    /**
     * Checks if the class has a Site_Subtype_3 property value.<p>
     * 
     * @return true if there is a Site_Subtype_3 property value.
     */
    boolean hasSite_Subtype_3();

    /**
     * Adds a Site_Subtype_3 property value.<p>
     * 
     * @param newSite_Subtype_3 the Site_Subtype_3 property value to be added
     */
    void addSite_Subtype_3(Object newSite_Subtype_3);

    /**
     * Removes a Site_Subtype_3 property value.<p>
     * 
     * @param oldSite_Subtype_3 the Site_Subtype_3 property value to be removed.
     */
    void removeSite_Subtype_3(Object oldSite_Subtype_3);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#Translocation_Name
     */
     
    /**
     * Gets all property values for the Translocation_Name property.<p>
     * 
     * @returns a collection of values for the Translocation_Name property.
     */
    Collection<? extends String> getTranslocation_Name();

    /**
     * Checks if the class has a Translocation_Name property value.<p>
     * 
     * @return true if there is a Translocation_Name property value.
     */
    boolean hasTranslocation_Name();

    /**
     * Adds a Translocation_Name property value.<p>
     * 
     * @param newTranslocation_Name the Translocation_Name property value to be added
     */
    void addTranslocation_Name(String newTranslocation_Name);

    /**
     * Removes a Translocation_Name property value.<p>
     * 
     * @param oldTranslocation_Name the Translocation_Name property value to be removed.
     */
    void removeTranslocation_Name(String oldTranslocation_Name);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
