package org.insightcentre.converter.impl.protegen.completefusionexport.impl;


import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Fusion_Id <br>
 * @version generated on Fri Nov 06 12:26:57 GMT 2015 by pc
 */

public interface Fusion_Id extends WrappedIndividual {

    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/completefusionexport#FusionIdLiteral
     */
     
    /**
     * Gets all property values for the FusionIdLiteral property.<p>
     * 
     * @returns a collection of values for the FusionIdLiteral property.
     */
    Collection<? extends Object> getFusionIdLiteral();

    /**
     * Checks if the class has a FusionIdLiteral property value.<p>
     * 
     * @return true if there is a FusionIdLiteral property value.
     */
    boolean hasFusionIdLiteral();

    /**
     * Adds a FusionIdLiteral property value.<p>
     * 
     * @param newFusionIdLiteral the FusionIdLiteral property value to be added
     */
    void addFusionIdLiteral(Object newFusionIdLiteral);

    /**
     * Removes a FusionIdLiteral property value.<p>
     * 
     * @param oldFusionIdLiteral the FusionIdLiteral property value to be removed.
     */
    void removeFusionIdLiteral(Object oldFusionIdLiteral);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
