package org.insightcentre.converter.impl.protegen.completefusionexport.impl;


import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Nov 06 12:26:57 GMT 2015 by pc
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://cosmic.sels.insight.org/schema/completefusionexport#Complete_Fusion_Export
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPLETE_FUSION_EXPORT.<p>
     * 
     */
    public static final OWLClass CLASS_COMPLETE_FUSION_EXPORT = factory.getOWLClass(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Complete_Fusion_Export"));

    /* ***************************************************
     * Class http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Id
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUSION_ID.<p>
     * 
     */
    public static final OWLClass CLASS_FUSION_ID = factory.getOWLClass(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Id"));

    /* ***************************************************
     * Object Property http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FUSION_ID.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FUSION_ID = factory.getOWLObjectProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Id"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#FusionIdLiteral
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FUSIONIDLITERAL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FUSIONIDLITERAL = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#FusionIdLiteral"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FUSION_TYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FUSION_TYPE = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Fusion_Type"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Histology_Subtype_1
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HISTOLOGY_SUBTYPE_1.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HISTOLOGY_SUBTYPE_1 = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Histology_Subtype_1"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Histology_Subtype_3
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HISTOLOGY_SUBTYPE_3.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HISTOLOGY_SUBTYPE_3 = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Histology_Subtype_3"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Primary_Site
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PRIMARY_SITE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PRIMARY_SITE = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Primary_Site"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Pubmed_PMID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PUBMED_PMID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PUBMED_PMID = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Pubmed_PMID"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Site_Subtype_1
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SITE_SUBTYPE_1.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SITE_SUBTYPE_1 = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Site_Subtype_1"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Site_Subtype_3
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SITE_SUBTYPE_3.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SITE_SUBTYPE_3 = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Site_Subtype_3"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#TranslocationNameLiteral
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TRANSLOCATIONNAMELITERAL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TRANSLOCATIONNAMELITERAL = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#TranslocationNameLiteral"));

    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#Translocation_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TRANSLOCATION_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TRANSLOCATION_NAME = factory.getOWLDataProperty(IRI.create("http://cosmic.sels.insight.org/schema/completefusionexport#Translocation_Name"));


}
