package org.insightcentre.converter.impl.protegen.completefusionexport.impl.impl;


import java.util.Collection;

import org.insightcentre.converter.impl.protegen.completefusionexport.impl.Fusion_Id;
import org.insightcentre.converter.impl.protegen.completefusionexport.impl.Vocabulary;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultFusion_Id <br>
 * @version generated on Fri Nov 06 12:26:57 GMT 2015 by pc
 */
public class DefaultFusion_Id extends WrappedIndividualImpl implements Fusion_Id {

    public DefaultFusion_Id(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/completefusionexport#FusionIdLiteral
     */
     
    public Collection<? extends Object> getFusionIdLiteral() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FUSIONIDLITERAL, Object.class);
    }

    public boolean hasFusionIdLiteral() {
		return !getFusionIdLiteral().isEmpty();
    }

    public void addFusionIdLiteral(Object newFusionIdLiteral) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FUSIONIDLITERAL, newFusionIdLiteral);
    }

    public void removeFusionIdLiteral(Object oldFusionIdLiteral) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FUSIONIDLITERAL, oldFusionIdLiteral);
    }


}
