package org.insightcentre.converter.impl.protegen.structuralgenomics.impl.impl;


import java.util.Collection;

import org.insightcentre.converter.impl.protegen.structuralgenomics.impl.Mutation_Id;
import org.insightcentre.converter.impl.protegen.structuralgenomics.impl.Vocabulary;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMutation_Id <br>
 * @version generated on Sat Oct 31 12:46:10 GMT 2015 by pc
 */
public class DefaultMutation_Id extends WrappedIndividualImpl implements Mutation_Id {

    public DefaultMutation_Id(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#MutationIdLiteral
     */
     
    public Collection<? extends Object> getMutationIdLiteral() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MUTATIONIDLITERAL, Object.class);
    }

    public boolean hasMutationIdLiteral() {
		return !getMutationIdLiteral().isEmpty();
    }

    public void addMutationIdLiteral(Object newMutationIdLiteral) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MUTATIONIDLITERAL, newMutationIdLiteral);
    }

    public void removeMutationIdLiteral(Object oldMutationIdLiteral) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MUTATIONIDLITERAL, oldMutationIdLiteral);
    }


}
