package org.insightcentre.converter.impl.protegen.methylation.impl;


import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Chromosome <br>
 * @version generated on Sat Oct 31 12:49:53 GMT 2015 by pc
 */

public interface Chromosome extends WrappedIndividual {

    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#ChromosomeNameLiteral
     */
     
    /**
     * Gets all property values for the ChromosomeNameLiteral property.<p>
     * 
     * @returns a collection of values for the ChromosomeNameLiteral property.
     */
    Collection<? extends Object> getChromosomeNameLiteral();

    /**
     * Checks if the class has a ChromosomeNameLiteral property value.<p>
     * 
     * @return true if there is a ChromosomeNameLiteral property value.
     */
    boolean hasChromosomeNameLiteral();

    /**
     * Adds a ChromosomeNameLiteral property value.<p>
     * 
     * @param newChromosomeNameLiteral the ChromosomeNameLiteral property value to be added
     */
    void addChromosomeNameLiteral(Object newChromosomeNameLiteral);

    /**
     * Removes a ChromosomeNameLiteral property value.<p>
     * 
     * @param oldChromosomeNameLiteral the ChromosomeNameLiteral property value to be removed.
     */
    void removeChromosomeNameLiteral(Object oldChromosomeNameLiteral);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
