package org.insightcentre.converter.impl.protegen.methylation.impl;


import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Gene_Name <br>
 * @version generated on Sat Oct 31 12:49:53 GMT 2015 by pc
 */

public interface Gene_Name extends WrappedIndividual {

    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#GeneNameLiteral
     */
     
    /**
     * Gets all property values for the GeneNameLiteral property.<p>
     * 
     * @returns a collection of values for the GeneNameLiteral property.
     */
    Collection<? extends Object> getGeneNameLiteral();

    /**
     * Checks if the class has a GeneNameLiteral property value.<p>
     * 
     * @return true if there is a GeneNameLiteral property value.
     */
    boolean hasGeneNameLiteral();

    /**
     * Adds a GeneNameLiteral property value.<p>
     * 
     * @param newGeneNameLiteral the GeneNameLiteral property value to be added
     */
    void addGeneNameLiteral(Object newGeneNameLiteral);

    /**
     * Removes a GeneNameLiteral property value.<p>
     * 
     * @param oldGeneNameLiteral the GeneNameLiteral property value to be removed.
     */
    void removeGeneNameLiteral(Object oldGeneNameLiteral);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
