package org.insightcentre.converter.impl.protegen.methylation.impl;


import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Methylation <br>
 * @version generated on Sat Oct 31 12:49:53 GMT 2015 by pc
 */

public interface Methylation extends WrappedIndividual {

    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Chromosome
     */
     
    /**
     * Gets all property values for the Chromosome property.<p>
     * 
     * @returns a collection of values for the Chromosome property.
     */
    Collection<? extends Chromosome> getChromosome();

    /**
     * Checks if the class has a Chromosome property value.<p>
     * 
     * @return true if there is a Chromosome property value.
     */
    boolean hasChromosome();

    /**
     * Adds a Chromosome property value.<p>
     * 
     * @param newChromosome the Chromosome property value to be added
     */
    void addChromosome(Chromosome newChromosome);

    /**
     * Removes a Chromosome property value.<p>
     * 
     * @param oldChromosome the Chromosome property value to be removed.
     */
    void removeChromosome(Chromosome oldChromosome);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Gene_Name
     */
     
    /**
     * Gets all property values for the Gene_Name property.<p>
     * 
     * @returns a collection of values for the Gene_Name property.
     */
    Collection<? extends Gene_Name> getGene_Name();

    /**
     * Checks if the class has a Gene_Name property value.<p>
     * 
     * @return true if there is a Gene_Name property value.
     */
    boolean hasGene_Name();

    /**
     * Adds a Gene_Name property value.<p>
     * 
     * @param newGene_Name the Gene_Name property value to be added
     */
    void addGene_Name(Gene_Name newGene_Name);

    /**
     * Removes a Gene_Name property value.<p>
     * 
     * @param oldGene_Name the Gene_Name property value to be removed.
     */
    void removeGene_Name(Gene_Name oldGene_Name);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Fragment_Id
     */
     
    /**
     * Gets all property values for the Fragment_Id property.<p>
     * 
     * @returns a collection of values for the Fragment_Id property.
     */
    Collection<? extends Object> getFragment_Id();

    /**
     * Checks if the class has a Fragment_Id property value.<p>
     * 
     * @return true if there is a Fragment_Id property value.
     */
    boolean hasFragment_Id();

    /**
     * Adds a Fragment_Id property value.<p>
     * 
     * @param newFragment_Id the Fragment_Id property value to be added
     */
    void addFragment_Id(Object newFragment_Id);

    /**
     * Removes a Fragment_Id property value.<p>
     * 
     * @param oldFragment_Id the Fragment_Id property value to be removed.
     */
    void removeFragment_Id(Object oldFragment_Id);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Histology_Subtype_1
     */
     
    /**
     * Gets all property values for the Histology_Subtype_1 property.<p>
     * 
     * @returns a collection of values for the Histology_Subtype_1 property.
     */
    Collection<? extends Object> getHistology_Subtype_1();

    /**
     * Checks if the class has a Histology_Subtype_1 property value.<p>
     * 
     * @return true if there is a Histology_Subtype_1 property value.
     */
    boolean hasHistology_Subtype_1();

    /**
     * Adds a Histology_Subtype_1 property value.<p>
     * 
     * @param newHistology_Subtype_1 the Histology_Subtype_1 property value to be added
     */
    void addHistology_Subtype_1(Object newHistology_Subtype_1);

    /**
     * Removes a Histology_Subtype_1 property value.<p>
     * 
     * @param oldHistology_Subtype_1 the Histology_Subtype_1 property value to be removed.
     */
    void removeHistology_Subtype_1(Object oldHistology_Subtype_1);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Histology_Subtype_3
     */
     
    /**
     * Gets all property values for the Histology_Subtype_3 property.<p>
     * 
     * @returns a collection of values for the Histology_Subtype_3 property.
     */
    Collection<? extends Object> getHistology_Subtype_3();

    /**
     * Checks if the class has a Histology_Subtype_3 property value.<p>
     * 
     * @return true if there is a Histology_Subtype_3 property value.
     */
    boolean hasHistology_Subtype_3();

    /**
     * Adds a Histology_Subtype_3 property value.<p>
     * 
     * @param newHistology_Subtype_3 the Histology_Subtype_3 property value to be added
     */
    void addHistology_Subtype_3(Object newHistology_Subtype_3);

    /**
     * Removes a Histology_Subtype_3 property value.<p>
     * 
     * @param oldHistology_Subtype_3 the Histology_Subtype_3 property value to be removed.
     */
    void removeHistology_Subtype_3(Object oldHistology_Subtype_3);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Id_Study
     */
     
    /**
     * Gets all property values for the Id_Study property.<p>
     * 
     * @returns a collection of values for the Id_Study property.
     */
    Collection<? extends Object> getId_Study();

    /**
     * Checks if the class has a Id_Study property value.<p>
     * 
     * @return true if there is a Id_Study property value.
     */
    boolean hasId_Study();

    /**
     * Adds a Id_Study property value.<p>
     * 
     * @param newId_Study the Id_Study property value to be added
     */
    void addId_Study(Object newId_Study);

    /**
     * Removes a Id_Study property value.<p>
     * 
     * @param oldId_Study the Id_Study property value to be removed.
     */
    void removeId_Study(Object oldId_Study);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Position
     */
     
    /**
     * Gets all property values for the Position property.<p>
     * 
     * @returns a collection of values for the Position property.
     */
    Collection<? extends Object> getPosition();

    /**
     * Checks if the class has a Position property value.<p>
     * 
     * @return true if there is a Position property value.
     */
    boolean hasPosition();

    /**
     * Adds a Position property value.<p>
     * 
     * @param newPosition the Position property value to be added
     */
    void addPosition(Object newPosition);

    /**
     * Removes a Position property value.<p>
     * 
     * @param oldPosition the Position property value to be removed.
     */
    void removePosition(Object oldPosition);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Primary_Histology
     */
     
    /**
     * Gets all property values for the Primary_Histology property.<p>
     * 
     * @returns a collection of values for the Primary_Histology property.
     */
    Collection<? extends Object> getPrimary_Histology();

    /**
     * Checks if the class has a Primary_Histology property value.<p>
     * 
     * @return true if there is a Primary_Histology property value.
     */
    boolean hasPrimary_Histology();

    /**
     * Adds a Primary_Histology property value.<p>
     * 
     * @param newPrimary_Histology the Primary_Histology property value to be added
     */
    void addPrimary_Histology(Object newPrimary_Histology);

    /**
     * Removes a Primary_Histology property value.<p>
     * 
     * @param oldPrimary_Histology the Primary_Histology property value to be removed.
     */
    void removePrimary_Histology(Object oldPrimary_Histology);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Site_Subtype_1
     */
     
    /**
     * Gets all property values for the Site_Subtype_1 property.<p>
     * 
     * @returns a collection of values for the Site_Subtype_1 property.
     */
    Collection<? extends Object> getSite_Subtype_1();

    /**
     * Checks if the class has a Site_Subtype_1 property value.<p>
     * 
     * @return true if there is a Site_Subtype_1 property value.
     */
    boolean hasSite_Subtype_1();

    /**
     * Adds a Site_Subtype_1 property value.<p>
     * 
     * @param newSite_Subtype_1 the Site_Subtype_1 property value to be added
     */
    void addSite_Subtype_1(Object newSite_Subtype_1);

    /**
     * Removes a Site_Subtype_1 property value.<p>
     * 
     * @param oldSite_Subtype_1 the Site_Subtype_1 property value to be removed.
     */
    void removeSite_Subtype_1(Object oldSite_Subtype_1);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/Methylation#Site_Subtype_3
     */
     
    /**
     * Gets all property values for the Site_Subtype_3 property.<p>
     * 
     * @returns a collection of values for the Site_Subtype_3 property.
     */
    Collection<? extends Object> getSite_Subtype_3();

    /**
     * Checks if the class has a Site_Subtype_3 property value.<p>
     * 
     * @return true if there is a Site_Subtype_3 property value.
     */
    boolean hasSite_Subtype_3();

    /**
     * Adds a Site_Subtype_3 property value.<p>
     * 
     * @param newSite_Subtype_3 the Site_Subtype_3 property value to be added
     */
    void addSite_Subtype_3(Object newSite_Subtype_3);

    /**
     * Removes a Site_Subtype_3 property value.<p>
     * 
     * @param oldSite_Subtype_3 the Site_Subtype_3 property value to be removed.
     */
    void removeSite_Subtype_3(Object oldSite_Subtype_3);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
