package org.insightcentre.converter.impl.protegen.structuralgenomics.impl;


import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: StructuralGenomicsArrangements <br>
 * @version generated on Sat Oct 31 12:46:10 GMT 2015 by pc
 */

public interface StructuralGenomicsArrangements extends WrappedIndividual {

    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Id_Tumour
     */
     
    /**
     * Gets all property values for the Id_Tumour property.<p>
     * 
     * @returns a collection of values for the Id_Tumour property.
     */
    Collection<? extends Id_Tumour> getId_Tumour();

    /**
     * Checks if the class has a Id_Tumour property value.<p>
     * 
     * @return true if there is a Id_Tumour property value.
     */
    boolean hasId_Tumour();

    /**
     * Adds a Id_Tumour property value.<p>
     * 
     * @param newId_Tumour the Id_Tumour property value to be added
     */
    void addId_Tumour(Id_Tumour newId_Tumour);

    /**
     * Removes a Id_Tumour property value.<p>
     * 
     * @param oldId_Tumour the Id_Tumour property value to be removed.
     */
    void removeId_Tumour(Id_Tumour oldId_Tumour);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Mutation_Id
     */
     
    /**
     * Gets all property values for the Mutation_Id property.<p>
     * 
     * @returns a collection of values for the Mutation_Id property.
     */
    Collection<? extends Mutation_Id> getMutation_Id();

    /**
     * Checks if the class has a Mutation_Id property value.<p>
     * 
     * @return true if there is a Mutation_Id property value.
     */
    boolean hasMutation_Id();

    /**
     * Adds a Mutation_Id property value.<p>
     * 
     * @param newMutation_Id the Mutation_Id property value to be added
     */
    void addMutation_Id(Mutation_Id newMutation_Id);

    /**
     * Removes a Mutation_Id property value.<p>
     * 
     * @param oldMutation_Id the Mutation_Id property value to be removed.
     */
    void removeMutation_Id(Mutation_Id oldMutation_Id);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Sample_Id
     */
     
    /**
     * Gets all property values for the Sample_Id property.<p>
     * 
     * @returns a collection of values for the Sample_Id property.
     */
    Collection<? extends Sample_Id> getSample_Id();

    /**
     * Checks if the class has a Sample_Id property value.<p>
     * 
     * @return true if there is a Sample_Id property value.
     */
    boolean hasSample_Id();

    /**
     * Adds a Sample_Id property value.<p>
     * 
     * @param newSample_Id the Sample_Id property value to be added
     */
    void addSample_Id(Sample_Id newSample_Id);

    /**
     * Removes a Sample_Id property value.<p>
     * 
     * @param oldSample_Id the Sample_Id property value to be removed.
     */
    void removeSample_Id(Sample_Id oldSample_Id);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Sample_Name
     */
     
    /**
     * Gets all property values for the Sample_Name property.<p>
     * 
     * @returns a collection of values for the Sample_Name property.
     */
    Collection<? extends Sample_Name> getSample_Name();

    /**
     * Checks if the class has a Sample_Name property value.<p>
     * 
     * @return true if there is a Sample_Name property value.
     */
    boolean hasSample_Name();

    /**
     * Adds a Sample_Name property value.<p>
     * 
     * @param newSample_Name the Sample_Name property value to be added
     */
    void addSample_Name(Sample_Name newSample_Name);

    /**
     * Removes a Sample_Name property value.<p>
     * 
     * @param oldSample_Name the Sample_Name property value to be removed.
     */
    void removeSample_Name(Sample_Name oldSample_Name);


    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Histology_Subtype_1
     */
     
    /**
     * Gets all property values for the Histology_Subtype_1 property.<p>
     * 
     * @returns a collection of values for the Histology_Subtype_1 property.
     */
    Collection<? extends Object> getHistology_Subtype_1();

    /**
     * Checks if the class has a Histology_Subtype_1 property value.<p>
     * 
     * @return true if there is a Histology_Subtype_1 property value.
     */
    boolean hasHistology_Subtype_1();

    /**
     * Adds a Histology_Subtype_1 property value.<p>
     * 
     * @param newHistology_Subtype_1 the Histology_Subtype_1 property value to be added
     */
    void addHistology_Subtype_1(Object newHistology_Subtype_1);

    /**
     * Removes a Histology_Subtype_1 property value.<p>
     * 
     * @param oldHistology_Subtype_1 the Histology_Subtype_1 property value to be removed.
     */
    void removeHistology_Subtype_1(Object oldHistology_Subtype_1);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Histology_Subtype_3
     */
     
    /**
     * Gets all property values for the Histology_Subtype_3 property.<p>
     * 
     * @returns a collection of values for the Histology_Subtype_3 property.
     */
    Collection<? extends Object> getHistology_Subtype_3();

    /**
     * Checks if the class has a Histology_Subtype_3 property value.<p>
     * 
     * @return true if there is a Histology_Subtype_3 property value.
     */
    boolean hasHistology_Subtype_3();

    /**
     * Adds a Histology_Subtype_3 property value.<p>
     * 
     * @param newHistology_Subtype_3 the Histology_Subtype_3 property value to be added
     */
    void addHistology_Subtype_3(Object newHistology_Subtype_3);

    /**
     * Removes a Histology_Subtype_3 property value.<p>
     * 
     * @param oldHistology_Subtype_3 the Histology_Subtype_3 property value to be removed.
     */
    void removeHistology_Subtype_3(Object oldHistology_Subtype_3);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Id_Study
     */
     
    /**
     * Gets all property values for the Id_Study property.<p>
     * 
     * @returns a collection of values for the Id_Study property.
     */
    Collection<? extends Object> getId_Study();

    /**
     * Checks if the class has a Id_Study property value.<p>
     * 
     * @return true if there is a Id_Study property value.
     */
    boolean hasId_Study();

    /**
     * Adds a Id_Study property value.<p>
     * 
     * @param newId_Study the Id_Study property value to be added
     */
    void addId_Study(Object newId_Study);

    /**
     * Removes a Id_Study property value.<p>
     * 
     * @param oldId_Study the Id_Study property value to be removed.
     */
    void removeId_Study(Object oldId_Study);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Mutation_Type
     */
     
    /**
     * Gets all property values for the Mutation_Type property.<p>
     * 
     * @returns a collection of values for the Mutation_Type property.
     */
    Collection<? extends Object> getMutation_Type();

    /**
     * Checks if the class has a Mutation_Type property value.<p>
     * 
     * @return true if there is a Mutation_Type property value.
     */
    boolean hasMutation_Type();

    /**
     * Adds a Mutation_Type property value.<p>
     * 
     * @param newMutation_Type the Mutation_Type property value to be added
     */
    void addMutation_Type(Object newMutation_Type);

    /**
     * Removes a Mutation_Type property value.<p>
     * 
     * @param oldMutation_Type the Mutation_Type property value to be removed.
     */
    void removeMutation_Type(Object oldMutation_Type);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Site_Subtype_1
     */
     
    /**
     * Gets all property values for the Site_Subtype_1 property.<p>
     * 
     * @returns a collection of values for the Site_Subtype_1 property.
     */
    Collection<? extends Object> getSite_Subtype_1();

    /**
     * Checks if the class has a Site_Subtype_1 property value.<p>
     * 
     * @return true if there is a Site_Subtype_1 property value.
     */
    boolean hasSite_Subtype_1();

    /**
     * Adds a Site_Subtype_1 property value.<p>
     * 
     * @param newSite_Subtype_1 the Site_Subtype_1 property value to be added
     */
    void addSite_Subtype_1(Object newSite_Subtype_1);

    /**
     * Removes a Site_Subtype_1 property value.<p>
     * 
     * @param oldSite_Subtype_1 the Site_Subtype_1 property value to be removed.
     */
    void removeSite_Subtype_1(Object oldSite_Subtype_1);



    /* ***************************************************
     * Property http://cosmic.sels.insight.org/schema/structuralgenomicarrangements#Site_Subtype_3
     */
     
    /**
     * Gets all property values for the Site_Subtype_3 property.<p>
     * 
     * @returns a collection of values for the Site_Subtype_3 property.
     */
    Collection<? extends Object> getSite_Subtype_3();

    /**
     * Checks if the class has a Site_Subtype_3 property value.<p>
     * 
     * @return true if there is a Site_Subtype_3 property value.
     */
    boolean hasSite_Subtype_3();

    /**
     * Adds a Site_Subtype_3 property value.<p>
     * 
     * @param newSite_Subtype_3 the Site_Subtype_3 property value to be added
     */
    void addSite_Subtype_3(Object newSite_Subtype_3);

    /**
     * Removes a Site_Subtype_3 property value.<p>
     * 
     * @param oldSite_Subtype_3 the Site_Subtype_3 property value to be removed.
     */
    void removeSite_Subtype_3(Object oldSite_Subtype_3);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
